name: Build and Deploy 

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - name: Install dependencies
      run: npm install

    - name: Build app
      run: npm run build

    - name: Build Docker image
      run: docker build -t w3bbbb/tech-store .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push image to Docker Hub
      run: docker push w3bbbb/tech-store

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to VPS via SSH
      run: |
        ssh -i ~/.ssh/id_ed25519 ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
          echo "Connected to EC2"
          docker pull w3bbbb/tech-store
          docker stop w3bbbb/tech-store || true
          docker rm w3bbbb/tech-store || true
          docker run -d --name w3bbbb/tech-store -p 80:80 w3bbbb/tech-store
        EOF
      # uses: appleboy/ssh-action@v1.0.3
      # with:
      #   host: ${{ secrets.VPS_HOST }}
      #   username: ${{ secrets.VPS_USER }}
      #   key: ${{ secrets.VPS_SSH_KEY }}
      #   script: |
      #     docker pull w3bbbb/tech-store
      #     docker stop w3bbbb/tech-store || true
      #     docker rm w3bbbb/tech-store || true
      #     docker run -d --name w3bbbb/tech-store -p 80:80 w3bbbb/tech-store
